name: test
on:
  workflow_dispatch:
  push:
    branches:
    - main
  pull_request:
    paths:
    - git_author_stats/**
    - pyproject.toml
    - setup.py
    - setup.cfg
    - pyproject.toml
    - tests/**
    - requirements.txt
    - tox.ini
    - .github/**
jobs:
  test:
    permissions:
      contents: write
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - windows-latest
        - macos-latest
        python:
        - 3.8
        - 3.9
        - '3.10'
        - 3.11
        - 3.12
    steps:
    - uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python }}
    - name: install
      run: make ci-install
    - name: configure git
      run: |
        git config --global user.email "$(git --no-pager show -s --format=%ae)"
        git config --global user.name "$(git --no-pager show -s --format=%an)"
    - name: test
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      stdout: true
      run: make test
